version: "3.7"
services:
  location-db:
    image: postgres
    volumes:
      - $PWD/location/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  inspection-db:
    image: postgres
    volumes:
      - $PWD/inspection/data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  nats:
    image: nats
    ports:
      - "4222:4222"
      - "8222:8222"