version: "3.7"
services:
  location-db:
    image: postgres
    volumes:
      - $PWD/location/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust