CREATE TABLE IF NOT EXISTS appointments (
	id UUID PRIMARY KEY,
	inspection_centre_id UUID NOT NULL,
	lead_id UUID NOT NULL,
	date DATE NOT NULL,
	timeslot INTEGER NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)